// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/types/supabase";

// Get environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const APP_URL = import.meta.env.VITE_APP_URL;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY || !APP_URL) {
  throw new Error('Missing Supabase environment variables');
}

// Create Supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: "pkce",
    storageKey: 'passguardia-auth',
    storage: window.localStorage,
  },
});

// Helper function to get site URL
export const getSiteURL = () => {
  let url =
    import.meta.env.VITE_SITE_URL ?? // Set this in your .env
    import.meta.env.VITE_APP_URL ?? // Automatic
    'http://localhost:5173/';
  
  // Make sure to include trailing slash
  url = url.charAt(url.length - 1) === '/' ? url : `${url}/`;
  
  return url;
};