name: Check Password Expiry

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 3 AM UTC (approximately 9 AM Nepal time)
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-passwords:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Supabase Function
        run: |
          curl -i --request POST \
          --url 'https://pongcqabtrrdzhynndps.functions.supabase.co/check-password-expiry' \
          --header 'Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_KEY }}'
